import Head from 'next/head'
import styles from '@/styles/Home.module.css'
import Link from 'next/link'

export default function Home() {

  return (
    <>
      <Head>
        <title>CryptoCheck</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${styles.main}`}>
        <h1>CryptoCheck</h1>
        <div className={styles.grid}>
          <Link href={"/overview"} className={styles.card}>
            <h2>Market Overview <span>-&gt;</span></h2>
            <p>Look at the latest news of the crypto market.</p>
          </Link>
          <Link href={"/coins"} className={styles.card}>
            <h2>All Coins <span>-&gt;</span></h2>
            <p>Retrieving the live data about all currencies.</p>
          </Link>
        </div>
      </main>
    </>
  )
}
